#!/bin/sh

#-------------------------------------------------------------------------------
# Name:        prelim2_folders.sh
# Purpose:     Delete contents of downstream folders before running all code
#		Copy images into Paper/Beamer_Figures that are not generated by
#		code but are part of slide deck
#
# Author:      Ryan
#
# Created:     17 April, 2020
#-------------------------------------------------------------------------------


if [ "$HOME" == "/Users/ericlewis" ]; then
        CODEDIR=$HOME/Documents/EconResearch2/HBP
        DBDIR="/Users/ericlewis/Documents/EconResearch2/HBP"
elif [ "$HOME" == "/c/Users/Ryan Kellogg" ]; then
        CODEDIR=C:/Work/HBP
        DBDIR="C:/Users/Ryan Kellogg/Dropbox/HBP"
elif [ "$HOME" == "/c/Users/Evan" ]; then
        CODEDIR=$HOME/Economics/Research/HBP
        DBDIR="C:/Users/Evan/Economics/Research/HBP"
fi


# DELETE ALL "CLEANED" RAW DATA AND INTERMEDIATE DATA FILES IN DROPBOX
find "$DBDIR/RawData/data" -type f -delete
find "$DBDIR/IntermediateData" -type f -delete

# DELETE ALL FIGURES AND TABLES STORED IN REPO RESULTS
find "$CODEDIR/Paper/Figures" -type f -delete
find "$CODEDIR/Paper/Beamer_Figures" -type f -delete

# DELETE COMPILED PAPER
rm "$CODEDIR/Paper/Tex/HKL_primaryterms.pdf"

# DELETE FEATHER DIRECTORIES
rm -r "$CODEDIR/ClusteringData"

# COPY IMAGES
cp "$DBDIR/Images/EIAShaleGasMap.pdf" "$CODEDIR/Paper/Beamer_Figures"
cp "$DBDIR/Images/fracking_schematic2.jpg" "$CODEDIR/Paper/Beamer_Figures"
cp "$DBDIR/Images/lease_schematic_EH.pdf" "$CODEDIR/Paper/Beamer_Figures"

# Clean up log files
rm *.log

exit
