ssc install shp2dta
ssc install scheme_tufte
ssc install latab
ssc install sutex2
ssc install findunique
ssc install rd
ssc install strdist
ssc install strgroup
ssc install rangestat
ssc install geodist
ssc install texify
ssc install texsave
ssc install filelist
net install http://www.stata-journal.com/software/sj14-2/st0085_2.pkg
ssc install _gwtmean
ssc install newey2
ssc install pathutil
ssc install kdens
ssc install moremata
ssc install egenmore
